#!/bin/sh
set -e

if ! git diff --cached --quiet -- home/cs2/autoexec.cfg home/cs2/render_binds.py; then
  python3 home/cs2/render_binds.py home/cs2/autoexec.cfg > home/cs2/binds.svg
  git add home/cs2/binds.svg
fi

if git diff --cached --quiet -- '*.nix' flake.lock; then
  exit 0
fi

nix fmt -- --ci
