keys:
  - &bunker age1h866gulvflkkyf67kafydjrue8pukv3epnml63n06gw39zgr0p4sjxjsl8

creation_rules:
  - path_regex: secrets/[^/]+\.env$
    key_groups:
    - age:
        - *bunker

  - path_regex: secrets/[^/]+\.(crt|key)$
    key_groups:
      - age:
        - *bunker
    format: binary
