keys:
  - &bunker age1m5m4w0udls8v9ewz6dk2d5sy50fc3ef020pa7ve5anetjakuludqhuyytl
  - &yorha2b age145sk8uy9j6dakef3jksl6224segq367k75lv4n4jjjtwly73vpkq6jkxzt
  - &yorha9s age144td7u09ty9lzjhxqtuvaz9kndx56tgv6x359vhadygxm8auxfhqsk0s9u
  - &yorhaA2 age1g0tsyuhutxpt8rfcu07t3t6fhrce4rq2a63l7yryly7hyp0a4fvspwyv8p

creation_rules:
  - path_regex: secrets/andrewyazura\.(crt|key)
    key_groups:
    - age:
      - *bunker
    format: binary

  - path_regex: secrets/ssh-config
    key_groups:
    - age:
      - *yorha2b
      - *yorha9s
      - *yorhaA2
    format: binary

  - path_regex: secrets/attic-env
    key_groups:
    - age:
      - *bunker
    format: binary

  - path_regex: secrets/netrc-bunker
    key_groups:
    - age:
      - *bunker
    format: binary

  - path_regex: secrets/netrc-yorha2b
    key_groups:
    - age:
      - *yorha2b
    format: binary

  - path_regex: secrets/netrc-yorha9s
    key_groups:
    - age:
      - *yorha9s
    format: binary

  - path_regex: secrets/netrc-yorhaA2
    key_groups:
    - age:
      - *yorhaA2
    format: binary
